#!/usr/bin/env python3
"""
Embed .env and serviceAccountKey.json into backend/app/_secrets.py
as encrypted constants.

Run this BEFORE PyInstaller build so that secrets are compiled into the exe.
No .env or serviceAccountKey.json files in the portable distribution.

Usage:
    python scripts/embed_secrets.py
"""
import os
import sys
import base64
import zlib
import secrets as _secrets_mod

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
BACKEND_DIR = os.path.join(PROJECT_ROOT, "backend")


def _encrypt(data: bytes, key: bytes) -> bytes:
    """Compress → XOR → base85 encode."""
    compressed = zlib.compress(data, 9)
    encrypted = bytes(b ^ key[i % len(key)] for i, b in enumerate(compressed))
    return base64.b85encode(encrypted)


def main() -> None:
    env_path = os.path.join(BACKEND_DIR, ".env")
    creds_path = os.path.join(BACKEND_DIR, "serviceAccountKey.json")
    output_path = os.path.join(BACKEND_DIR, "app", "_secrets.py")

    # ── Validate inputs ───────────────────────────────────────────────────
    for path, label in [(env_path, ".env"), (creds_path, "serviceAccountKey.json")]:
        if not os.path.exists(path):
            print(f"ERROR: {label} not found at {path}", file=sys.stderr)
            sys.exit(1)

    # ── Read source files ─────────────────────────────────────────────────
    with open(env_path, "rb") as f:
        env_data = f.read()
    with open(creds_path, "rb") as f:
        creds_data = f.read()

    # ── Generate random key & encrypt ─────────────────────────────────────
    key = _secrets_mod.token_bytes(32)
    enc_env = _encrypt(env_data, key)
    enc_creds = _encrypt(creds_data, key)

    # ── Generate Python module ────────────────────────────────────────────
    source = f'''"""
Auto-generated by scripts/embed_secrets.py — DO NOT edit or commit.
Encrypted .env and serviceAccountKey.json for PyInstaller bundle.
"""
import base64
import json
import os
import zlib

_K = {key!r}
_E = {enc_env!r}
_C = {enc_creds!r}


def _d(data: bytes) -> bytes:
    """Decode + XOR decrypt + decompress."""
    raw = base64.b85decode(data)
    dec = bytes(b ^ _K[i % len(_K)] for i, b in enumerate(raw))
    return zlib.decompress(dec)


def load_env() -> None:
    """Decrypt .env values and inject into os.environ."""
    text = _d(_E).decode("utf-8")
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" in line:
            k, _, v = line.partition("=")
            os.environ.setdefault(k.strip(), v.strip())


def get_credentials_dict() -> dict:
    """Decrypt serviceAccountKey.json and return as dict (in-memory only)."""
    return json.loads(_d(_C))
'''

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(source)

    print(f"  OK  Secrets embedded -> {output_path}")
    print(f"      .env ({len(env_data)} bytes) + serviceAccountKey.json ({len(creds_data)} bytes)")


if __name__ == "__main__":
    main()
